package lime;


import lime.utils.Assets;


class AssetData {

	private static var initialized:Bool = false;
	
	public static var library = new #if haxe3 Map <String, #else Hash <#end LibraryType> ();
	public static var path = new #if haxe3 Map <String, #else Hash <#end String> ();
	public static var type = new #if haxe3 Map <String, #else Hash <#end AssetType> ();	
	
	public static function initialize():Void {
		
		if (!initialized) {
			
			path.set ("assets/data/data-goes-here.txt", "assets/data/data-goes-here.txt");
			type.set ("assets/data/data-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/level.png", "assets/data/level.png");
			type.set ("assets/data/level.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/level1.png", "assets/data/level1.png");
			type.set ("assets/data/level1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/level2.png", "assets/data/level2.png");
			type.set ("assets/data/level2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/level3.png", "assets/data/level3.png");
			type.set ("assets/data/level3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/tileset.png", "assets/data/tileset.png");
			type.set ("assets/data/tileset.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/fonts/vera.ttf", "assets/fonts/vera.ttf");
			type.set ("assets/fonts/vera.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/verab.ttf", "assets/fonts/verab.ttf");
			type.set ("assets/fonts/verab.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/verai.ttf", "assets/fonts/verai.ttf");
			type.set ("assets/fonts/verai.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/veraz.ttf", "assets/fonts/veraz.ttf");
			type.set ("assets/fonts/veraz.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/gfx/other/icon_party.png", "assets/gfx/other/icon_party.png");
			type.set ("assets/gfx/other/icon_party.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/other/portrait_mane.png", "assets/gfx/other/portrait_mane.png");
			type.set ("assets/gfx/other/portrait_mane.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/blue.png", "assets/gfx/ui/buttons/blue.png");
			type.set ("assets/gfx/ui/buttons/blue.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/blue_back.png", "assets/gfx/ui/buttons/blue_back.png");
			type.set ("assets/gfx/ui/buttons/blue_back.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/blue_back_over.png", "assets/gfx/ui/buttons/blue_back_over.png");
			type.set ("assets/gfx/ui/buttons/blue_back_over.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/blue_over.png", "assets/gfx/ui/buttons/blue_over.png");
			type.set ("assets/gfx/ui/buttons/blue_over.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_blue.png", "assets/gfx/ui/buttons/button_blue.png");
			type.set ("assets/gfx/ui/buttons/button_blue.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_blue_scale_0.png", "assets/gfx/ui/buttons/button_blue_scale_0.png");
			type.set ("assets/gfx/ui/buttons/button_blue_scale_0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_blue_scale_1.png", "assets/gfx/ui/buttons/button_blue_scale_1.png");
			type.set ("assets/gfx/ui/buttons/button_blue_scale_1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_blue_scale_2.png", "assets/gfx/ui/buttons/button_blue_scale_2.png");
			type.set ("assets/gfx/ui/buttons/button_blue_scale_2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_blue_scale_all.png", "assets/gfx/ui/buttons/button_blue_scale_all.png");
			type.set ("assets/gfx/ui/buttons/button_blue_scale_all.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_blue_scale_all2.png", "assets/gfx/ui/buttons/button_blue_scale_all2.png");
			type.set ("assets/gfx/ui/buttons/button_blue_scale_all2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_blue_toggle.png", "assets/gfx/ui/buttons/button_blue_toggle.png");
			type.set ("assets/gfx/ui/buttons/button_blue_toggle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_confirmation_black.png", "assets/gfx/ui/buttons/button_confirmation_black.png");
			type.set ("assets/gfx/ui/buttons/button_confirmation_black.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_confirmation_over.png", "assets/gfx/ui/buttons/button_confirmation_over.png");
			type.set ("assets/gfx/ui/buttons/button_confirmation_over.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_confirmation_red_over.png", "assets/gfx/ui/buttons/button_confirmation_red_over.png");
			type.set ("assets/gfx/ui/buttons/button_confirmation_red_over.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_confirmation_red_up.png", "assets/gfx/ui/buttons/button_confirmation_red_up.png");
			type.set ("assets/gfx/ui/buttons/button_confirmation_red_up.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_confirmation_up.png", "assets/gfx/ui/buttons/button_confirmation_up.png");
			type.set ("assets/gfx/ui/buttons/button_confirmation_up.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_gold.png", "assets/gfx/ui/buttons/button_gold.png");
			type.set ("assets/gfx/ui/buttons/button_gold.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_gold_up.png", "assets/gfx/ui/buttons/button_gold_up.png");
			type.set ("assets/gfx/ui/buttons/button_gold_up.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_grey.png", "assets/gfx/ui/buttons/button_grey.png");
			type.set ("assets/gfx/ui/buttons/button_grey.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/button_red.png", "assets/gfx/ui/buttons/button_red.png");
			type.set ("assets/gfx/ui/buttons/button_red.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/gold.png", "assets/gfx/ui/buttons/gold.png");
			type.set ("assets/gfx/ui/buttons/gold.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/gold_over.png", "assets/gfx/ui/buttons/gold_over.png");
			type.set ("assets/gfx/ui/buttons/gold_over.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/grey.png", "assets/gfx/ui/buttons/grey.png");
			type.set ("assets/gfx/ui/buttons/grey.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/grey_over.png", "assets/gfx/ui/buttons/grey_over.png");
			type.set ("assets/gfx/ui/buttons/grey_over.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/master_button_blue.png", "assets/gfx/ui/buttons/master_button_blue.png");
			type.set ("assets/gfx/ui/buttons/master_button_blue.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/red.png", "assets/gfx/ui/buttons/red.png");
			type.set ("assets/gfx/ui/buttons/red.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/red_over.png", "assets/gfx/ui/buttons/red_over.png");
			type.set ("assets/gfx/ui/buttons/red_over.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/tab_grey.png", "assets/gfx/ui/buttons/tab_grey.png");
			type.set ("assets/gfx/ui/buttons/tab_grey.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/tab_grey_back.png", "assets/gfx/ui/buttons/tab_grey_back.png");
			type.set ("assets/gfx/ui/buttons/tab_grey_back.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/tab_grey_back_over.png", "assets/gfx/ui/buttons/tab_grey_back_over.png");
			type.set ("assets/gfx/ui/buttons/tab_grey_back_over.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/buttons/tab_grey_over.png", "assets/gfx/ui/buttons/tab_grey_over.png");
			type.set ("assets/gfx/ui/buttons/tab_grey_over.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/chrome/dark_grey.png", "assets/gfx/ui/chrome/dark_grey.png");
			type.set ("assets/gfx/ui/chrome/dark_grey.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/chrome/dark_grey_flat_top.png", "assets/gfx/ui/chrome/dark_grey_flat_top.png");
			type.set ("assets/gfx/ui/chrome/dark_grey_flat_top.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/chrome/dark_grey_inset.png", "assets/gfx/ui/chrome/dark_grey_inset.png");
			type.set ("assets/gfx/ui/chrome/dark_grey_inset.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/chrome/dark_grey_texture.png", "assets/gfx/ui/chrome/dark_grey_texture.png");
			type.set ("assets/gfx/ui/chrome/dark_grey_texture.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/misc/check_big.png", "assets/gfx/ui/misc/check_big.png");
			type.set ("assets/gfx/ui/misc/check_big.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/misc/check_box_big.png", "assets/gfx/ui/misc/check_box_big.png");
			type.set ("assets/gfx/ui/misc/check_box_big.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/misc/check_box_small.png", "assets/gfx/ui/misc/check_box_small.png");
			type.set ("assets/gfx/ui/misc/check_box_small.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/misc/check_small.png", "assets/gfx/ui/misc/check_small.png");
			type.set ("assets/gfx/ui/misc/check_small.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/misc/flag_blank.png", "assets/gfx/ui/misc/flag_blank.png");
			type.set ("assets/gfx/ui/misc/flag_blank.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/misc/health_bar.png", "assets/gfx/ui/misc/health_bar.png");
			type.set ("assets/gfx/ui/misc/health_bar.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/misc/mana_bar.png", "assets/gfx/ui/misc/mana_bar.png");
			type.set ("assets/gfx/ui/misc/mana_bar.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/misc/radio.png", "assets/gfx/ui/misc/radio.png");
			type.set ("assets/gfx/ui/misc/radio.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/misc/radio_dot.png", "assets/gfx/ui/misc/radio_dot.png");
			type.set ("assets/gfx/ui/misc/radio_dot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/saveslot.png", "assets/gfx/ui/saveslot.png");
			type.set ("assets/gfx/ui/saveslot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/saveslot_shadow.png", "assets/gfx/ui/saveslot_shadow.png");
			type.set ("assets/gfx/ui/saveslot_shadow.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/save_menu_overlay.png", "assets/gfx/ui/save_menu_overlay.png");
			type.set ("assets/gfx/ui/save_menu_overlay.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/title_back.png", "assets/gfx/ui/title_back.png");
			type.set ("assets/gfx/ui/title_back.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/ui/title_back2.png", "assets/gfx/ui/title_back2.png");
			type.set ("assets/gfx/ui/title_back2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ASE/DeathBall.ase", "assets/images/ASE/DeathBall.ase");
			type.set ("assets/images/ASE/DeathBall.ase", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/ASE/Tower.ase", "assets/images/ASE/Tower.ase");
			type.set ("assets/images/ASE/Tower.ase", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/ASE/tower_earth.ase", "assets/images/ASE/tower_earth.ase");
			type.set ("assets/images/ASE/tower_earth.ase", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/ASE/tower_earth.png", "assets/images/ASE/tower_earth.png");
			type.set ("assets/images/ASE/tower_earth.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/ASE/tower_water.ase", "assets/images/ASE/tower_water.ase");
			type.set ("assets/images/ASE/tower_water.ase", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/ASE/tower_water.png", "assets/images/ASE/tower_water.png");
			type.set ("assets/images/ASE/tower_water.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/coin.png", "assets/images/coin.png");
			type.set ("assets/images/coin.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/enemy-0.png", "assets/images/enemy-0.png");
			type.set ("assets/images/enemy-0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/enemy-1.png", "assets/images/enemy-1.png");
			type.set ("assets/images/enemy-1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Flixoul.png", "assets/images/Flixoul.png");
			type.set ("assets/images/Flixoul.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/images-go-here.txt", "assets/images/images-go-here.txt");
			type.set ("assets/images/images-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/map.png", "assets/images/map.png");
			type.set ("assets/images/map.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles1.png", "assets/images/tiles1.png");
			type.set ("assets/images/tiles1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tizles.png", "assets/images/tizles.png");
			type.set ("assets/images/tizles.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tower.png", "assets/images/tower.png");
			type.set ("assets/images/tower.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tower_earth.png", "assets/images/tower_earth.png");
			type.set ("assets/images/tower_earth.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tower_fire.png", "assets/images/tower_fire.png");
			type.set ("assets/images/tower_fire.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tower_water.png", "assets/images/tower_water.png");
			type.set ("assets/images/tower_water.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Zombie.png", "assets/images/Zombie.png");
			type.set ("assets/images/Zombie.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/levels.png", "assets/levels.png");
			type.set ("assets/levels.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/en-US/fontss.xml", "assets/locales/en-US/fontss.xml");
			type.set ("assets/locales/en-US/fontss.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/locales/en-US/uius.csv", "assets/locales/en-US/uius.csv");
			type.set ("assets/locales/en-US/uius.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/locales/index.xml", "assets/locales/index.xml");
			type.set ("assets/locales/index.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/locales/nb-NO/fonts.xml", "assets/locales/nb-NO/fonts.xml");
			type.set ("assets/locales/nb-NO/fonts.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/locales/nb-NO/ui.csv", "assets/locales/nb-NO/ui.csv");
			type.set ("assets/locales/nb-NO/ui.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/locales/_flags/cs-CZ.png", "assets/locales/_flags/cs-CZ.png");
			type.set ("assets/locales/_flags/cs-CZ.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/_flags/de-DE.png", "assets/locales/_flags/de-DE.png");
			type.set ("assets/locales/_flags/de-DE.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/_flags/en-CA.png", "assets/locales/_flags/en-CA.png");
			type.set ("assets/locales/_flags/en-CA.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/_flags/en-GB.png", "assets/locales/_flags/en-GB.png");
			type.set ("assets/locales/_flags/en-GB.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/_flags/en-US.png", "assets/locales/_flags/en-US.png");
			type.set ("assets/locales/_flags/en-US.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/_flags/es-ES.png", "assets/locales/_flags/es-ES.png");
			type.set ("assets/locales/_flags/es-ES.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/_flags/fr-FR.png", "assets/locales/_flags/fr-FR.png");
			type.set ("assets/locales/_flags/fr-FR.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/_flags/it-IT.png", "assets/locales/_flags/it-IT.png");
			type.set ("assets/locales/_flags/it-IT.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/_flags/ja-JP.png", "assets/locales/_flags/ja-JP.png");
			type.set ("assets/locales/_flags/ja-JP.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/_flags/ko-KR.png", "assets/locales/_flags/ko-KR.png");
			type.set ("assets/locales/_flags/ko-KR.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/_flags/nb-NO.png", "assets/locales/_flags/nb-NO.png");
			type.set ("assets/locales/_flags/nb-NO.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/_flags/pl-PL.png", "assets/locales/_flags/pl-PL.png");
			type.set ("assets/locales/_flags/pl-PL.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/locales/_flags/yo-DA.png", "assets/locales/_flags/yo-DA.png");
			type.set ("assets/locales/_flags/yo-DA.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/music/music-goes-here.txt", "assets/music/music-goes-here.txt");
			type.set ("assets/music/music-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/sounds-go-here.txt", "assets/sounds/sounds-go-here.txt");
			type.set ("assets/sounds/sounds-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/tiled/example.tmx", "assets/tiled/example.tmx");
			type.set ("assets/tiled/example.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/tiled/mainLevel.tmx", "assets/tiled/mainLevel.tmx");
			type.set ("assets/tiled/mainLevel.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/tiled/maps.tmx", "assets/tiled/maps.tmx");
			type.set ("assets/tiled/maps.tmx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/tiled/tileset.png", "assets/tiled/tileset.png");
			type.set ("assets/tiled/tileset.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/tiled/tileset.tsx", "assets/tiled/tileset.tsx");
			type.set ("assets/tiled/tileset.tsx", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/xml/Menu.xml", "assets/xml/Menu.xml");
			type.set ("assets/xml/Menu.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/xml/_ui_globals.xml", "assets/xml/_ui_globals.xml");
			type.set ("assets/xml/_ui_globals.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("flixel/sounds/beep.ogg", "flixel/sounds/beep.ogg");
			type.set ("flixel/sounds/beep.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flixel/sounds/flixel.ogg", "flixel/sounds/flixel.ogg");
			type.set ("flixel/sounds/flixel.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flixel/fonts/nokiafc22.ttf", "flixel/fonts/nokiafc22.ttf");
			type.set ("flixel/fonts/nokiafc22.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("flixel/fonts/monsterrat.ttf", "flixel/fonts/monsterrat.ttf");
			type.set ("flixel/fonts/monsterrat.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("flixel/images/ui/button.png", "flixel/images/ui/button.png");
			type.set ("flixel/images/ui/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/images/logo/default.png", "flixel/images/logo/default.png");
			type.set ("flixel/images/logo/default.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/box.png", "flixel/flixel-ui/img/box.png");
			type.set ("flixel/flixel-ui/img/box.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button.png", "flixel/flixel-ui/img/button.png");
			type.set ("flixel/flixel-ui/img/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_arrow_down.png", "flixel/flixel-ui/img/button_arrow_down.png");
			type.set ("flixel/flixel-ui/img/button_arrow_down.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_arrow_left.png", "flixel/flixel-ui/img/button_arrow_left.png");
			type.set ("flixel/flixel-ui/img/button_arrow_left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_arrow_right.png", "flixel/flixel-ui/img/button_arrow_right.png");
			type.set ("flixel/flixel-ui/img/button_arrow_right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_arrow_up.png", "flixel/flixel-ui/img/button_arrow_up.png");
			type.set ("flixel/flixel-ui/img/button_arrow_up.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_thin.png", "flixel/flixel-ui/img/button_thin.png");
			type.set ("flixel/flixel-ui/img/button_thin.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_toggle.png", "flixel/flixel-ui/img/button_toggle.png");
			type.set ("flixel/flixel-ui/img/button_toggle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/check_box.png", "flixel/flixel-ui/img/check_box.png");
			type.set ("flixel/flixel-ui/img/check_box.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/check_mark.png", "flixel/flixel-ui/img/check_mark.png");
			type.set ("flixel/flixel-ui/img/check_mark.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/chrome.png", "flixel/flixel-ui/img/chrome.png");
			type.set ("flixel/flixel-ui/img/chrome.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/chrome_flat.png", "flixel/flixel-ui/img/chrome_flat.png");
			type.set ("flixel/flixel-ui/img/chrome_flat.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/chrome_inset.png", "flixel/flixel-ui/img/chrome_inset.png");
			type.set ("flixel/flixel-ui/img/chrome_inset.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/chrome_light.png", "flixel/flixel-ui/img/chrome_light.png");
			type.set ("flixel/flixel-ui/img/chrome_light.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/dropdown_mark.png", "flixel/flixel-ui/img/dropdown_mark.png");
			type.set ("flixel/flixel-ui/img/dropdown_mark.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/finger_big.png", "flixel/flixel-ui/img/finger_big.png");
			type.set ("flixel/flixel-ui/img/finger_big.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/finger_small.png", "flixel/flixel-ui/img/finger_small.png");
			type.set ("flixel/flixel-ui/img/finger_small.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/hilight.png", "flixel/flixel-ui/img/hilight.png");
			type.set ("flixel/flixel-ui/img/hilight.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/invis.png", "flixel/flixel-ui/img/invis.png");
			type.set ("flixel/flixel-ui/img/invis.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/minus_mark.png", "flixel/flixel-ui/img/minus_mark.png");
			type.set ("flixel/flixel-ui/img/minus_mark.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/plus_mark.png", "flixel/flixel-ui/img/plus_mark.png");
			type.set ("flixel/flixel-ui/img/plus_mark.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/radio.png", "flixel/flixel-ui/img/radio.png");
			type.set ("flixel/flixel-ui/img/radio.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/radio_dot.png", "flixel/flixel-ui/img/radio_dot.png");
			type.set ("flixel/flixel-ui/img/radio_dot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/swatch.png", "flixel/flixel-ui/img/swatch.png");
			type.set ("flixel/flixel-ui/img/swatch.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/tab.png", "flixel/flixel-ui/img/tab.png");
			type.set ("flixel/flixel-ui/img/tab.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/tab_back.png", "flixel/flixel-ui/img/tab_back.png");
			type.set ("flixel/flixel-ui/img/tab_back.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/tooltip_arrow.png", "flixel/flixel-ui/img/tooltip_arrow.png");
			type.set ("flixel/flixel-ui/img/tooltip_arrow.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/xml/defaults.xml", "flixel/flixel-ui/xml/defaults.xml");
			type.set ("flixel/flixel-ui/xml/defaults.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("flixel/flixel-ui/xml/default_loading_screen.xml", "flixel/flixel-ui/xml/default_loading_screen.xml");
			type.set ("flixel/flixel-ui/xml/default_loading_screen.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("flixel/flixel-ui/xml/default_popup.xml", "flixel/flixel-ui/xml/default_popup.xml");
			type.set ("flixel/flixel-ui/xml/default_popup.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			
			
			initialized = true;
			
		} //!initialized
		
	} //initialize
	
	
} //AssetData
